/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as activities from "../activities.js";
import type * as contact from "../contact.js";
import type * as dashboard from "../dashboard.js";
import type * as documents from "../documents.js";
import type * as evidence from "../evidence.js";
import type * as holdings from "../holdings.js";
import type * as listings from "../listings.js";
import type * as messages from "../messages.js";
import type * as notifications from "../notifications.js";
import type * as orders from "../orders.js";
import type * as priceHistory from "../priceHistory.js";
import type * as projects from "../projects.js";
import type * as users from "../users.js";
import type * as verification from "../verification.js";
import type * as wallets from "../wallets.js";
import type * as wasteRecords from "../wasteRecords.js";
import type * as watchlists from "../watchlists.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  activities: typeof activities;
  contact: typeof contact;
  dashboard: typeof dashboard;
  documents: typeof documents;
  evidence: typeof evidence;
  holdings: typeof holdings;
  listings: typeof listings;
  messages: typeof messages;
  notifications: typeof notifications;
  orders: typeof orders;
  priceHistory: typeof priceHistory;
  projects: typeof projects;
  users: typeof users;
  verification: typeof verification;
  wallets: typeof wallets;
  wasteRecords: typeof wasteRecords;
  watchlists: typeof watchlists;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
